version: '3.4'

services:
  db:
    image: rest-api-udemy-course-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - 3304:3306
    networks:
      - udemy-network
  rest-api-udemy-course:
    image: rest-api-udemy-course
    build:
      context: .
      dockerfile: RESTAPIUdemyCourse\Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44384:80
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge
